package com.travisolbrich.scavenger.hunt;

public class TestTokens {
    public static final String adminUser = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiQWRtaW4gVXNlciIsImdpdmVuX25hbWUiOiJhZG1pbkdpdmVuIiwiZmFtaWx5X25hbWUiOiJhZG1pbkZhbWlseSIsImVtYWlsIjoiYWRtaW5AbG9jYWxob3N0IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInJvbGVzIjpbIlJPTEVfQURNSU4iLCJST0xFX1VTRVIiLCJ0ZXN0Il0sImlzcyI6Imh0dHBzOi8vdHJhdmlzb2xicmljaC5hdXRoMC5jb20vIiwic3ViIjoidGVzdHwxIiwiYXVkIjoiMkhKd2xiblVhVjhuaVVqOXV5TDZMRXN4T1doUjFURkciLCJleHAiOjY0NjI2OTE3MTIsImlhdCI6MTQ2MjY1NTcxMn0.VIn1kitCgRi57aTm2lMnBBMNCHltdAhEJ2R69ir7m9k";
    public static final String regularUser = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiUmVndWxhciBVc2VyIiwiZ2l2ZW5fbmFtZSI6InJlZ3VsYXJHaXZlbiIsImZhbWlseV9uYW1lIjoicmVndWxhckZhbWlseSIsImVtYWlsIjoicmVndWxhckBsb2NhbGhvc3QiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHBzOi8vdHJhdmlzb2xicmljaC5hdXRoMC5jb20vIiwic3ViIjoidGVzdHwyIiwiYXVkIjoiMkhKd2xiblVhVjhuaVVqOXV5TDZMRXN4T1doUjFURkciLCJleHAiOjY0NjI2OTE3MTIsImlhdCI6MTQ2MjY1NTcxMn0.yooteFvOGyKwur8b1HO0cNFYi3Z-v-GWqeaYeueI2vk";
}
